# Generated by Django 4.2 on 2024-04-14 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('composer', models.CharField(max_length=220)),
                ('milliseconds', models.IntegerField()),
                ('bytes', models.IntegerField()),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disks.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disks.artist'),
        ),
    ]
