# Generated by Django 4.2 on 2024-04-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
